package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyComment;

public interface LjyCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_comment
     *
     * @mbg.generated
     */
    int insert(LjyComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_comment
     *
     * @mbg.generated
     */
    LjyComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_comment
     *
     * @mbg.generated
     */
    List<LjyComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyComment record);
}