package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyHotelOrder;

public interface LjyHotelOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_order
     *
     * @mbg.generated
     */
    int insert(LjyHotelOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_order
     *
     * @mbg.generated
     */
    LjyHotelOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_order
     *
     * @mbg.generated
     */
    List<LjyHotelOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyHotelOrder record);
}