package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyHotelTradingArea;

public interface LjyHotelTradingAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_trading_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_trading_area
     *
     * @mbg.generated
     */
    int insert(LjyHotelTradingArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_trading_area
     *
     * @mbg.generated
     */
    LjyHotelTradingArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_trading_area
     *
     * @mbg.generated
     */
    List<LjyHotelTradingArea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_trading_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyHotelTradingArea record);
}