package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyHotel;

public interface LjyHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel
     *
     * @mbg.generated
     */
    int insert(LjyHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel
     *
     * @mbg.generated
     */
    LjyHotel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel
     *
     * @mbg.generated
     */
    List<LjyHotel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyHotel record);
}