package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyHotelTempStore;

public interface LjyHotelTempStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_temp_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_temp_store
     *
     * @mbg.generated
     */
    int insert(LjyHotelTempStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_temp_store
     *
     * @mbg.generated
     */
    LjyHotelTempStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_temp_store
     *
     * @mbg.generated
     */
    List<LjyHotelTempStore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_hotel_temp_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyHotelTempStore record);
}