package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyLabelDic;

public interface LjyLabelDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_label_dic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_label_dic
     *
     * @mbg.generated
     */
    int insert(LjyLabelDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_label_dic
     *
     * @mbg.generated
     */
    LjyLabelDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_label_dic
     *
     * @mbg.generated
     */
    List<LjyLabelDic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_label_dic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyLabelDic record);
}