package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyOrderLinkUser;

public interface LjyOrderLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_order_link_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_order_link_user
     *
     * @mbg.generated
     */
    int insert(LjyOrderLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_order_link_user
     *
     * @mbg.generated
     */
    LjyOrderLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_order_link_user
     *
     * @mbg.generated
     */
    List<LjyOrderLinkUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_order_link_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyOrderLinkUser record);
}