package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyProductStore;

public interface LjyProductStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_product_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_product_store
     *
     * @mbg.generated
     */
    int insert(LjyProductStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_product_store
     *
     * @mbg.generated
     */
    LjyProductStore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_product_store
     *
     * @mbg.generated
     */
    List<LjyProductStore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_product_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyProductStore record);
}