package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyTradeEnds;

public interface LjyTradeEndsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_trade_ends
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_trade_ends
     *
     * @mbg.generated
     */
    int insert(LjyTradeEnds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_trade_ends
     *
     * @mbg.generated
     */
    LjyTradeEnds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_trade_ends
     *
     * @mbg.generated
     */
    List<LjyTradeEnds> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_trade_ends
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyTradeEnds record);
}