package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyUser;

public interface LjyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user
     *
     * @mbg.generated
     */
    int insert(LjyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user
     *
     * @mbg.generated
     */
    LjyUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user
     *
     * @mbg.generated
     */
    List<LjyUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyUser record);
}