package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyUserInfo;

public interface LjyUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_info
     *
     * @mbg.generated
     */
    int insert(LjyUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_info
     *
     * @mbg.generated
     */
    LjyUserInfo selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_info
     *
     * @mbg.generated
     */
    List<LjyUserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyUserInfo record);
}