package org.lanqiao.mapper;

import java.util.List;
import org.lanqiao.beans.pojo.LjyUserLinkUser;

public interface LjyUserLinkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_link_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_link_user
     *
     * @mbg.generated
     */
    int insert(LjyUserLinkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_link_user
     *
     * @mbg.generated
     */
    LjyUserLinkUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_link_user
     *
     * @mbg.generated
     */
    List<LjyUserLinkUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ljy_user_link_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LjyUserLinkUser record);
}