package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 * Database Table Remarks:
 *   评论表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_comment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyComment {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   如果产品是酒店的话 改字段保存酒店id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.hotelId
     *
     * @mbg.generated
     */
    private Long hotelid;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.productId
     *
     * @mbg.generated
     */
    private Long productid;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     * Database Column Remarks:
     *   商品类型(0:旅游产品 1:酒店产品 2:机票产品)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.productType
     *
     * @mbg.generated
     */
    private Integer producttype;

    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   是否包含图片(当用户上传评论时检测)0:无图片 1:有图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.isHavingImg
     *
     * @mbg.generated
     */
    private Integer ishavingimg;

    /**
     * Database Column Remarks:
     *   位置评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.positionScore
     *
     * @mbg.generated
     */
    private Integer positionscore;

    /**
     * Database Column Remarks:
     *   设施评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.facilitiesScore
     *
     * @mbg.generated
     */
    private Integer facilitiesscore;

    /**
     * Database Column Remarks:
     *   服务评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.serviceScore
     *
     * @mbg.generated
     */
    private Integer servicescore;

    /**
     * Database Column Remarks:
     *   卫生评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.hygieneScore
     *
     * @mbg.generated
     */
    private Integer hygienescore;

    /**
     * Database Column Remarks:
     *   综合评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * Database Column Remarks:
     *   出游类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.tripMode
     *
     * @mbg.generated
     */
    private Long tripmode;

    /**
     * Database Column Remarks:
     *   是否满意（0：有待改善 1：值得推荐）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.isOk
     *
     * @mbg.generated
     */
    private Integer isok;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.id
     *
     * @return the value of ljy_comment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.id
     *
     * @param id the value for ljy_comment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.hotelId
     *
     * @return the value of ljy_comment.hotelId
     *
     * @mbg.generated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.hotelId
     *
     * @param hotelid the value for ljy_comment.hotelId
     *
     * @mbg.generated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.productId
     *
     * @return the value of ljy_comment.productId
     *
     * @mbg.generated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.productId
     *
     * @param productid the value for ljy_comment.productId
     *
     * @mbg.generated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.orderId
     *
     * @return the value of ljy_comment.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.orderId
     *
     * @param orderid the value for ljy_comment.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.productType
     *
     * @return the value of ljy_comment.productType
     *
     * @mbg.generated
     */
    public Integer getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.productType
     *
     * @param producttype the value for ljy_comment.productType
     *
     * @mbg.generated
     */
    public void setProducttype(Integer producttype) {
        this.producttype = producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.userId
     *
     * @return the value of ljy_comment.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.userId
     *
     * @param userid the value for ljy_comment.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.isHavingImg
     *
     * @return the value of ljy_comment.isHavingImg
     *
     * @mbg.generated
     */
    public Integer getIshavingimg() {
        return ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.isHavingImg
     *
     * @param ishavingimg the value for ljy_comment.isHavingImg
     *
     * @mbg.generated
     */
    public void setIshavingimg(Integer ishavingimg) {
        this.ishavingimg = ishavingimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.positionScore
     *
     * @return the value of ljy_comment.positionScore
     *
     * @mbg.generated
     */
    public Integer getPositionscore() {
        return positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.positionScore
     *
     * @param positionscore the value for ljy_comment.positionScore
     *
     * @mbg.generated
     */
    public void setPositionscore(Integer positionscore) {
        this.positionscore = positionscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.facilitiesScore
     *
     * @return the value of ljy_comment.facilitiesScore
     *
     * @mbg.generated
     */
    public Integer getFacilitiesscore() {
        return facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.facilitiesScore
     *
     * @param facilitiesscore the value for ljy_comment.facilitiesScore
     *
     * @mbg.generated
     */
    public void setFacilitiesscore(Integer facilitiesscore) {
        this.facilitiesscore = facilitiesscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.serviceScore
     *
     * @return the value of ljy_comment.serviceScore
     *
     * @mbg.generated
     */
    public Integer getServicescore() {
        return servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.serviceScore
     *
     * @param servicescore the value for ljy_comment.serviceScore
     *
     * @mbg.generated
     */
    public void setServicescore(Integer servicescore) {
        this.servicescore = servicescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.hygieneScore
     *
     * @return the value of ljy_comment.hygieneScore
     *
     * @mbg.generated
     */
    public Integer getHygienescore() {
        return hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.hygieneScore
     *
     * @param hygienescore the value for ljy_comment.hygieneScore
     *
     * @mbg.generated
     */
    public void setHygienescore(Integer hygienescore) {
        this.hygienescore = hygienescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.score
     *
     * @return the value of ljy_comment.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.score
     *
     * @param score the value for ljy_comment.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.tripMode
     *
     * @return the value of ljy_comment.tripMode
     *
     * @mbg.generated
     */
    public Long getTripmode() {
        return tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.tripMode
     *
     * @param tripmode the value for ljy_comment.tripMode
     *
     * @mbg.generated
     */
    public void setTripmode(Long tripmode) {
        this.tripmode = tripmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.isOk
     *
     * @return the value of ljy_comment.isOk
     *
     * @mbg.generated
     */
    public Integer getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.isOk
     *
     * @param isok the value for ljy_comment.isOk
     *
     * @mbg.generated
     */
    public void setIsok(Integer isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.creationDate
     *
     * @return the value of ljy_comment.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.creationDate
     *
     * @param creationdate the value for ljy_comment.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.createdBy
     *
     * @return the value of ljy_comment.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.createdBy
     *
     * @param createdby the value for ljy_comment.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.modifyDate
     *
     * @return the value of ljy_comment.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.modifyDate
     *
     * @param modifydate the value for ljy_comment.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.modifiedBy
     *
     * @return the value of ljy_comment.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.modifiedBy
     *
     * @param modifiedby the value for ljy_comment.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_comment.content
     *
     * @return the value of ljy_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_comment.content
     *
     * @param content the value for ljy_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}