package org.lanqiao.beans.pojo;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_hotel_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyHotelOrder {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   订单类型(0:旅游产品 1:酒店产品 2：机票产品)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.orderType
     *
     * @mbg.generated
     */
    private Integer ordertype;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.orderNo
     *
     * @mbg.generated
     */
    private String orderno;

    /**
     * Database Column Remarks:
     *   交易编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.tradeNo
     *
     * @mbg.generated
     */
    private String tradeno;

    /**
     * Database Column Remarks:
     *   冗余字段 酒店id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.hotelId
     *
     * @mbg.generated
     */
    private Long hotelid;

    /**
     * Database Column Remarks:
     *   冗余字段 酒店名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.hotelName
     *
     * @mbg.generated
     */
    private String hotelname;

    /**
     * Database Column Remarks:
     *   房间id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.roomId
     *
     * @mbg.generated
     */
    private Long roomid;

    /**
     * Database Column Remarks:
     *   消耗数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   预订天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.bookingDays
     *
     * @mbg.generated
     */
    private Integer bookingdays;

    /**
     * Database Column Remarks:
     *   入住时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.checkInDate
     *
     * @mbg.generated
     */
    private Date checkindate;

    /**
     * Database Column Remarks:
     *   退房时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.checkOutDate
     *
     * @mbg.generated
     */
    private Date checkoutdate;

    /**
     * Database Column Remarks:
     *   订单状态（0：待支付 1:已取消 2:支付成功 3:已消费 4：已点评）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.orderStatus
     *
     * @mbg.generated
     */
    private Integer orderstatus;

    /**
     * Database Column Remarks:
     *   支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.payAmount
     *
     * @mbg.generated
     */
    private BigDecimal payamount;

    /**
     * Database Column Remarks:
     *   支付方式:1:支付宝 2:微信 3:到店付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.payType
     *
     * @mbg.generated
     */
    private Integer paytype;

    /**
     * Database Column Remarks:
     *   联系手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.noticePhone
     *
     * @mbg.generated
     */
    private String noticephone;

    /**
     * Database Column Remarks:
     *   联系邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.noticeEmail
     *
     * @mbg.generated
     */
    private String noticeemail;

    /**
     * Database Column Remarks:
     *   是否需要发票（0：不需要 1：需要）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.isNeedInvoice
     *
     * @mbg.generated
     */
    private Integer isneedinvoice;

    /**
     * Database Column Remarks:
     *   发票类型（0：个人 1：公司）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.invoiceType
     *
     * @mbg.generated
     */
    private Integer invoicetype;

    /**
     * Database Column Remarks:
     *   发票抬头
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.invoiceHead
     *
     * @mbg.generated
     */
    private String invoicehead;

    /**
     * Database Column Remarks:
     *   入住人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.linkUserName
     *
     * @mbg.generated
     */
    private String linkusername;

    /**
     * Database Column Remarks:
     *   0:WEB端 1:手机端 2:其他客户端
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.bookType
     *
     * @mbg.generated
     */
    private Integer booktype;

    /**
     * Database Column Remarks:
     *   预定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     * Database Column Remarks:
     *   支付完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * Database Column Remarks:
     *   特殊需求
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel_order.specialRequirement
     *
     * @mbg.generated
     */
    private String specialrequirement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.id
     *
     * @return the value of ljy_hotel_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.id
     *
     * @param id the value for ljy_hotel_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.userId
     *
     * @return the value of ljy_hotel_order.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.userId
     *
     * @param userid the value for ljy_hotel_order.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.orderType
     *
     * @return the value of ljy_hotel_order.orderType
     *
     * @mbg.generated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.orderType
     *
     * @param ordertype the value for ljy_hotel_order.orderType
     *
     * @mbg.generated
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.orderNo
     *
     * @return the value of ljy_hotel_order.orderNo
     *
     * @mbg.generated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.orderNo
     *
     * @param orderno the value for ljy_hotel_order.orderNo
     *
     * @mbg.generated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.tradeNo
     *
     * @return the value of ljy_hotel_order.tradeNo
     *
     * @mbg.generated
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.tradeNo
     *
     * @param tradeno the value for ljy_hotel_order.tradeNo
     *
     * @mbg.generated
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.hotelId
     *
     * @return the value of ljy_hotel_order.hotelId
     *
     * @mbg.generated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.hotelId
     *
     * @param hotelid the value for ljy_hotel_order.hotelId
     *
     * @mbg.generated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.hotelName
     *
     * @return the value of ljy_hotel_order.hotelName
     *
     * @mbg.generated
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.hotelName
     *
     * @param hotelname the value for ljy_hotel_order.hotelName
     *
     * @mbg.generated
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.roomId
     *
     * @return the value of ljy_hotel_order.roomId
     *
     * @mbg.generated
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.roomId
     *
     * @param roomid the value for ljy_hotel_order.roomId
     *
     * @mbg.generated
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.count
     *
     * @return the value of ljy_hotel_order.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.count
     *
     * @param count the value for ljy_hotel_order.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.bookingDays
     *
     * @return the value of ljy_hotel_order.bookingDays
     *
     * @mbg.generated
     */
    public Integer getBookingdays() {
        return bookingdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.bookingDays
     *
     * @param bookingdays the value for ljy_hotel_order.bookingDays
     *
     * @mbg.generated
     */
    public void setBookingdays(Integer bookingdays) {
        this.bookingdays = bookingdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.checkInDate
     *
     * @return the value of ljy_hotel_order.checkInDate
     *
     * @mbg.generated
     */
    public Date getCheckindate() {
        return checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.checkInDate
     *
     * @param checkindate the value for ljy_hotel_order.checkInDate
     *
     * @mbg.generated
     */
    public void setCheckindate(Date checkindate) {
        this.checkindate = checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.checkOutDate
     *
     * @return the value of ljy_hotel_order.checkOutDate
     *
     * @mbg.generated
     */
    public Date getCheckoutdate() {
        return checkoutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.checkOutDate
     *
     * @param checkoutdate the value for ljy_hotel_order.checkOutDate
     *
     * @mbg.generated
     */
    public void setCheckoutdate(Date checkoutdate) {
        this.checkoutdate = checkoutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.orderStatus
     *
     * @return the value of ljy_hotel_order.orderStatus
     *
     * @mbg.generated
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.orderStatus
     *
     * @param orderstatus the value for ljy_hotel_order.orderStatus
     *
     * @mbg.generated
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.payAmount
     *
     * @return the value of ljy_hotel_order.payAmount
     *
     * @mbg.generated
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.payAmount
     *
     * @param payamount the value for ljy_hotel_order.payAmount
     *
     * @mbg.generated
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.payType
     *
     * @return the value of ljy_hotel_order.payType
     *
     * @mbg.generated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.payType
     *
     * @param paytype the value for ljy_hotel_order.payType
     *
     * @mbg.generated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.noticePhone
     *
     * @return the value of ljy_hotel_order.noticePhone
     *
     * @mbg.generated
     */
    public String getNoticephone() {
        return noticephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.noticePhone
     *
     * @param noticephone the value for ljy_hotel_order.noticePhone
     *
     * @mbg.generated
     */
    public void setNoticephone(String noticephone) {
        this.noticephone = noticephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.noticeEmail
     *
     * @return the value of ljy_hotel_order.noticeEmail
     *
     * @mbg.generated
     */
    public String getNoticeemail() {
        return noticeemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.noticeEmail
     *
     * @param noticeemail the value for ljy_hotel_order.noticeEmail
     *
     * @mbg.generated
     */
    public void setNoticeemail(String noticeemail) {
        this.noticeemail = noticeemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.isNeedInvoice
     *
     * @return the value of ljy_hotel_order.isNeedInvoice
     *
     * @mbg.generated
     */
    public Integer getIsneedinvoice() {
        return isneedinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.isNeedInvoice
     *
     * @param isneedinvoice the value for ljy_hotel_order.isNeedInvoice
     *
     * @mbg.generated
     */
    public void setIsneedinvoice(Integer isneedinvoice) {
        this.isneedinvoice = isneedinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.invoiceType
     *
     * @return the value of ljy_hotel_order.invoiceType
     *
     * @mbg.generated
     */
    public Integer getInvoicetype() {
        return invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.invoiceType
     *
     * @param invoicetype the value for ljy_hotel_order.invoiceType
     *
     * @mbg.generated
     */
    public void setInvoicetype(Integer invoicetype) {
        this.invoicetype = invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.invoiceHead
     *
     * @return the value of ljy_hotel_order.invoiceHead
     *
     * @mbg.generated
     */
    public String getInvoicehead() {
        return invoicehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.invoiceHead
     *
     * @param invoicehead the value for ljy_hotel_order.invoiceHead
     *
     * @mbg.generated
     */
    public void setInvoicehead(String invoicehead) {
        this.invoicehead = invoicehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.linkUserName
     *
     * @return the value of ljy_hotel_order.linkUserName
     *
     * @mbg.generated
     */
    public String getLinkusername() {
        return linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.linkUserName
     *
     * @param linkusername the value for ljy_hotel_order.linkUserName
     *
     * @mbg.generated
     */
    public void setLinkusername(String linkusername) {
        this.linkusername = linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.bookType
     *
     * @return the value of ljy_hotel_order.bookType
     *
     * @mbg.generated
     */
    public Integer getBooktype() {
        return booktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.bookType
     *
     * @param booktype the value for ljy_hotel_order.bookType
     *
     * @mbg.generated
     */
    public void setBooktype(Integer booktype) {
        this.booktype = booktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.creationDate
     *
     * @return the value of ljy_hotel_order.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.creationDate
     *
     * @param creationdate the value for ljy_hotel_order.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.createdBy
     *
     * @return the value of ljy_hotel_order.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.createdBy
     *
     * @param createdby the value for ljy_hotel_order.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.modifyDate
     *
     * @return the value of ljy_hotel_order.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.modifyDate
     *
     * @param modifydate the value for ljy_hotel_order.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.modifiedBy
     *
     * @return the value of ljy_hotel_order.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.modifiedBy
     *
     * @param modifiedby the value for ljy_hotel_order.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel_order.specialRequirement
     *
     * @return the value of ljy_hotel_order.specialRequirement
     *
     * @mbg.generated
     */
    public String getSpecialrequirement() {
        return specialrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel_order.specialRequirement
     *
     * @param specialrequirement the value for ljy_hotel_order.specialRequirement
     *
     * @mbg.generated
     */
    public void setSpecialrequirement(String specialrequirement) {
        this.specialrequirement = specialrequirement;
    }
}