package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 * Database Table Remarks:
 *   酒店表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_hotel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyHotel {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   酒店名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.hotelName
     *
     * @mbg.generated
     */
    private String hotelname;

    /**
     * Database Column Remarks:
     *   所在国家id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.countryId
     *
     * @mbg.generated
     */
    private Long countryid;

    /**
     * Database Column Remarks:
     *   所在省份id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.provinceId
     *
     * @mbg.generated
     */
    private Long provinceid;

    /**
     * Database Column Remarks:
     *   所在城市id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.cityId
     *
     * @mbg.generated
     */
    private Long cityid;

    /**
     * Database Column Remarks:
     *   酒店所在地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   酒店介绍（保存附文本）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     * Database Column Remarks:
     *   酒店设施
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.facilities
     *
     * @mbg.generated
     */
    private String facilities;

    /**
     * Database Column Remarks:
     *   酒店政策
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.hotelPolicy
     *
     * @mbg.generated
     */
    private String hotelpolicy;

    /**
     * Database Column Remarks:
     *   酒店类型(1:国内酒店 2:国际酒店)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.hotelType
     *
     * @mbg.generated
     */
    private Integer hoteltype;

    /**
     * Database Column Remarks:
     *   (1:经济酒店  2:二星级酒店  3:三星级 4:四星酒店 5星酒店)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.hotelLevel
     *
     * @mbg.generated
     */
    private Integer hotellevel;

    /**
     * Database Column Remarks:
     *   是否是团购酒店
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.isGroupPurchase
     *
     * @mbg.generated
     */
    private Integer isgrouppurchase;

    /**
     * Database Column Remarks:
     *   城市名称 冗余字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.redundantCityName
     *
     * @mbg.generated
     */
    private String redundantcityname;

    /**
     * Database Column Remarks:
     *   省名称 冗余字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.redundantProvinceName
     *
     * @mbg.generated
     */
    private String redundantprovincename;

    /**
     * Database Column Remarks:
     *   国家名称 冗余字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.redundantCountryName
     *
     * @mbg.generated
     */
    private String redundantcountryname;

    /**
     * Database Column Remarks:
     *   酒店库存（冗余，每天开定时任务的时候更新）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.redundantHotelStore
     *
     * @mbg.generated
     */
    private Integer redundanthotelstore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_hotel.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.id
     *
     * @return the value of ljy_hotel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.id
     *
     * @param id the value for ljy_hotel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.hotelName
     *
     * @return the value of ljy_hotel.hotelName
     *
     * @mbg.generated
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.hotelName
     *
     * @param hotelname the value for ljy_hotel.hotelName
     *
     * @mbg.generated
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.countryId
     *
     * @return the value of ljy_hotel.countryId
     *
     * @mbg.generated
     */
    public Long getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.countryId
     *
     * @param countryid the value for ljy_hotel.countryId
     *
     * @mbg.generated
     */
    public void setCountryid(Long countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.provinceId
     *
     * @return the value of ljy_hotel.provinceId
     *
     * @mbg.generated
     */
    public Long getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.provinceId
     *
     * @param provinceid the value for ljy_hotel.provinceId
     *
     * @mbg.generated
     */
    public void setProvinceid(Long provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.cityId
     *
     * @return the value of ljy_hotel.cityId
     *
     * @mbg.generated
     */
    public Long getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.cityId
     *
     * @param cityid the value for ljy_hotel.cityId
     *
     * @mbg.generated
     */
    public void setCityid(Long cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.address
     *
     * @return the value of ljy_hotel.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.address
     *
     * @param address the value for ljy_hotel.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.details
     *
     * @return the value of ljy_hotel.details
     *
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.details
     *
     * @param details the value for ljy_hotel.details
     *
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.facilities
     *
     * @return the value of ljy_hotel.facilities
     *
     * @mbg.generated
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.facilities
     *
     * @param facilities the value for ljy_hotel.facilities
     *
     * @mbg.generated
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.hotelPolicy
     *
     * @return the value of ljy_hotel.hotelPolicy
     *
     * @mbg.generated
     */
    public String getHotelpolicy() {
        return hotelpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.hotelPolicy
     *
     * @param hotelpolicy the value for ljy_hotel.hotelPolicy
     *
     * @mbg.generated
     */
    public void setHotelpolicy(String hotelpolicy) {
        this.hotelpolicy = hotelpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.hotelType
     *
     * @return the value of ljy_hotel.hotelType
     *
     * @mbg.generated
     */
    public Integer getHoteltype() {
        return hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.hotelType
     *
     * @param hoteltype the value for ljy_hotel.hotelType
     *
     * @mbg.generated
     */
    public void setHoteltype(Integer hoteltype) {
        this.hoteltype = hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.hotelLevel
     *
     * @return the value of ljy_hotel.hotelLevel
     *
     * @mbg.generated
     */
    public Integer getHotellevel() {
        return hotellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.hotelLevel
     *
     * @param hotellevel the value for ljy_hotel.hotelLevel
     *
     * @mbg.generated
     */
    public void setHotellevel(Integer hotellevel) {
        this.hotellevel = hotellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.isGroupPurchase
     *
     * @return the value of ljy_hotel.isGroupPurchase
     *
     * @mbg.generated
     */
    public Integer getIsgrouppurchase() {
        return isgrouppurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.isGroupPurchase
     *
     * @param isgrouppurchase the value for ljy_hotel.isGroupPurchase
     *
     * @mbg.generated
     */
    public void setIsgrouppurchase(Integer isgrouppurchase) {
        this.isgrouppurchase = isgrouppurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.redundantCityName
     *
     * @return the value of ljy_hotel.redundantCityName
     *
     * @mbg.generated
     */
    public String getRedundantcityname() {
        return redundantcityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.redundantCityName
     *
     * @param redundantcityname the value for ljy_hotel.redundantCityName
     *
     * @mbg.generated
     */
    public void setRedundantcityname(String redundantcityname) {
        this.redundantcityname = redundantcityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.redundantProvinceName
     *
     * @return the value of ljy_hotel.redundantProvinceName
     *
     * @mbg.generated
     */
    public String getRedundantprovincename() {
        return redundantprovincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.redundantProvinceName
     *
     * @param redundantprovincename the value for ljy_hotel.redundantProvinceName
     *
     * @mbg.generated
     */
    public void setRedundantprovincename(String redundantprovincename) {
        this.redundantprovincename = redundantprovincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.redundantCountryName
     *
     * @return the value of ljy_hotel.redundantCountryName
     *
     * @mbg.generated
     */
    public String getRedundantcountryname() {
        return redundantcountryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.redundantCountryName
     *
     * @param redundantcountryname the value for ljy_hotel.redundantCountryName
     *
     * @mbg.generated
     */
    public void setRedundantcountryname(String redundantcountryname) {
        this.redundantcountryname = redundantcountryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.redundantHotelStore
     *
     * @return the value of ljy_hotel.redundantHotelStore
     *
     * @mbg.generated
     */
    public Integer getRedundanthotelstore() {
        return redundanthotelstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.redundantHotelStore
     *
     * @param redundanthotelstore the value for ljy_hotel.redundantHotelStore
     *
     * @mbg.generated
     */
    public void setRedundanthotelstore(Integer redundanthotelstore) {
        this.redundanthotelstore = redundanthotelstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.creationDate
     *
     * @return the value of ljy_hotel.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.creationDate
     *
     * @param creationdate the value for ljy_hotel.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.createdBy
     *
     * @return the value of ljy_hotel.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.createdBy
     *
     * @param createdby the value for ljy_hotel.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.modifyDate
     *
     * @return the value of ljy_hotel.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.modifyDate
     *
     * @param modifydate the value for ljy_hotel.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_hotel.modifiedBy
     *
     * @return the value of ljy_hotel.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_hotel.modifiedBy
     *
     * @param modifiedby the value for ljy_hotel.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}