package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 * Database Table Remarks:
 *   标签字典表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_label_dic
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyLabelDic {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   key值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   value值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   父级标签id(1级标签则为0)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.parentId
     *
     * @mbg.generated
     */
    private Long parentid;

    /**
     * Database Column Remarks:
     *   标签图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_label_dic.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.id
     *
     * @return the value of ljy_label_dic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.id
     *
     * @param id the value for ljy_label_dic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.name
     *
     * @return the value of ljy_label_dic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.name
     *
     * @param name the value for ljy_label_dic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.value
     *
     * @return the value of ljy_label_dic.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.value
     *
     * @param value the value for ljy_label_dic.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.description
     *
     * @return the value of ljy_label_dic.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.description
     *
     * @param description the value for ljy_label_dic.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.parentId
     *
     * @return the value of ljy_label_dic.parentId
     *
     * @mbg.generated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.parentId
     *
     * @param parentid the value for ljy_label_dic.parentId
     *
     * @mbg.generated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.pic
     *
     * @return the value of ljy_label_dic.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.pic
     *
     * @param pic the value for ljy_label_dic.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.creationDate
     *
     * @return the value of ljy_label_dic.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.creationDate
     *
     * @param creationdate the value for ljy_label_dic.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.createdBy
     *
     * @return the value of ljy_label_dic.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.createdBy
     *
     * @param createdby the value for ljy_label_dic.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.modifyDate
     *
     * @return the value of ljy_label_dic.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.modifyDate
     *
     * @param modifydate the value for ljy_label_dic.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_label_dic.modifiedBy
     *
     * @return the value of ljy_label_dic.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_label_dic.modifiedBy
     *
     * @param modifiedby the value for ljy_label_dic.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}