package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_order_link_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyOrderLinkUser {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     * Database Column Remarks:
     *   联系人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.linkUserId
     *
     * @mbg.generated
     */
    private Long linkuserid;

    /**
     * Database Column Remarks:
     *   入住人姓名逗号分隔
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.linkUserName
     *
     * @mbg.generated
     */
    private String linkusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_order_link_user.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.id
     *
     * @return the value of ljy_order_link_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.id
     *
     * @param id the value for ljy_order_link_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.orderId
     *
     * @return the value of ljy_order_link_user.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.orderId
     *
     * @param orderid the value for ljy_order_link_user.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.linkUserId
     *
     * @return the value of ljy_order_link_user.linkUserId
     *
     * @mbg.generated
     */
    public Long getLinkuserid() {
        return linkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.linkUserId
     *
     * @param linkuserid the value for ljy_order_link_user.linkUserId
     *
     * @mbg.generated
     */
    public void setLinkuserid(Long linkuserid) {
        this.linkuserid = linkuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.linkUserName
     *
     * @return the value of ljy_order_link_user.linkUserName
     *
     * @mbg.generated
     */
    public String getLinkusername() {
        return linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.linkUserName
     *
     * @param linkusername the value for ljy_order_link_user.linkUserName
     *
     * @mbg.generated
     */
    public void setLinkusername(String linkusername) {
        this.linkusername = linkusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.creationDate
     *
     * @return the value of ljy_order_link_user.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.creationDate
     *
     * @param creationdate the value for ljy_order_link_user.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.createdBy
     *
     * @return the value of ljy_order_link_user.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.createdBy
     *
     * @param createdby the value for ljy_order_link_user.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.modifyDate
     *
     * @return the value of ljy_order_link_user.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.modifyDate
     *
     * @param modifydate the value for ljy_order_link_user.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_order_link_user.modifiedBy
     *
     * @return the value of ljy_order_link_user.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_order_link_user.modifiedBy
     *
     * @param modifiedby the value for ljy_order_link_user.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}