package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyUser {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   若是第三方登录，系统将自动生成唯一账号；自注册用户则为邮箱或者手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.userCode
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     * Database Column Remarks:
     *   若是第三方登录，系统将自动生成唯一密码；自注册用户则为自定义密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.userPassword
     *
     * @mbg.generated
     */
    private String userpassword;

    /**
     * Database Column Remarks:
     *   用户类型（标识：0 自注册用户 1 微信登录 2 QQ登录 3 微博登录）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.userType
     *
     * @mbg.generated
     */
    private Integer usertype;

    /**
     * Database Column Remarks:
     *   平台ID（根据不同登录用户，进行相应存入：自注册用户主键ID、微信ID、QQID、微博ID）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.flatID
     *
     * @mbg.generated
     */
    private Long flatid;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   微信号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.weChat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     * Database Column Remarks:
     *   qq账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.QQ
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * Database Column Remarks:
     *   微博账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.weibo
     *
     * @mbg.generated
     */
    private String weibo;

    /**
     * Database Column Remarks:
     *   百度账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.baidu
     *
     * @mbg.generated
     */
    private String baidu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * Database Column Remarks:
     *   是否激活,(0 false，1 true,默认是0)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user.activated
     *
     * @mbg.generated
     */
    private Integer activated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.id
     *
     * @return the value of ljy_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.id
     *
     * @param id the value for ljy_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.userCode
     *
     * @return the value of ljy_user.userCode
     *
     * @mbg.generated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.userCode
     *
     * @param usercode the value for ljy_user.userCode
     *
     * @mbg.generated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.userPassword
     *
     * @return the value of ljy_user.userPassword
     *
     * @mbg.generated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.userPassword
     *
     * @param userpassword the value for ljy_user.userPassword
     *
     * @mbg.generated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.userType
     *
     * @return the value of ljy_user.userType
     *
     * @mbg.generated
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.userType
     *
     * @param usertype the value for ljy_user.userType
     *
     * @mbg.generated
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.flatID
     *
     * @return the value of ljy_user.flatID
     *
     * @mbg.generated
     */
    public Long getFlatid() {
        return flatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.flatID
     *
     * @param flatid the value for ljy_user.flatID
     *
     * @mbg.generated
     */
    public void setFlatid(Long flatid) {
        this.flatid = flatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.userName
     *
     * @return the value of ljy_user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.userName
     *
     * @param username the value for ljy_user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.weChat
     *
     * @return the value of ljy_user.weChat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.weChat
     *
     * @param wechat the value for ljy_user.weChat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.QQ
     *
     * @return the value of ljy_user.QQ
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.QQ
     *
     * @param qq the value for ljy_user.QQ
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.weibo
     *
     * @return the value of ljy_user.weibo
     *
     * @mbg.generated
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.weibo
     *
     * @param weibo the value for ljy_user.weibo
     *
     * @mbg.generated
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.baidu
     *
     * @return the value of ljy_user.baidu
     *
     * @mbg.generated
     */
    public String getBaidu() {
        return baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.baidu
     *
     * @param baidu the value for ljy_user.baidu
     *
     * @mbg.generated
     */
    public void setBaidu(String baidu) {
        this.baidu = baidu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.creationDate
     *
     * @return the value of ljy_user.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.creationDate
     *
     * @param creationdate the value for ljy_user.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.createdBy
     *
     * @return the value of ljy_user.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.createdBy
     *
     * @param createdby the value for ljy_user.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.modifyDate
     *
     * @return the value of ljy_user.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.modifyDate
     *
     * @param modifydate the value for ljy_user.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.modifiedBy
     *
     * @return the value of ljy_user.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.modifiedBy
     *
     * @param modifiedby the value for ljy_user.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user.activated
     *
     * @return the value of ljy_user.activated
     *
     * @mbg.generated
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user.activated
     *
     * @param activated the value for ljy_user.activated
     *
     * @mbg.generated
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }
}