package org.lanqiao.beans.pojo;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ljy_user_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LjyUserInfo {
    /**
     * Database Column Remarks:
     *   主键,外键对应用户表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     * Database Column Remarks:
     *   用户昵称，冗余字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.userIcon
     *
     * @mbg.generated
     */
    private String usericon;

    /**
     * Database Column Remarks:
     *   徽标，是否vip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.vip
     *
     * @mbg.generated
     */
    private Integer vip;

    /**
     * Database Column Remarks:
     *   徽标，是否舵
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.rudder
     *
     * @mbg.generated
     */
    private Integer rudder;

    /**
     * Database Column Remarks:
     *   徽标，是否指路人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.guide
     *
     * @mbg.generated
     */
    private Integer guide;

    /**
     * Database Column Remarks:
     *   关注数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.attention
     *
     * @mbg.generated
     */
    private Long attention;

    /**
     * Database Column Remarks:
     *   粉丝数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.fans
     *
     * @mbg.generated
     */
    private Long fans;

    /**
     * Database Column Remarks:
     *   蜂蜜数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.honey
     *
     * @mbg.generated
     */
    private Long honey;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   个人介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.birthDate
     *
     * @mbg.generated
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.creationDate
     *
     * @mbg.generated
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.createdBy
     *
     * @mbg.generated
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ljy_user_info.modifiedBy
     *
     * @mbg.generated
     */
    private Long modifiedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.userId
     *
     * @return the value of ljy_user_info.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.userId
     *
     * @param userid the value for ljy_user_info.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.username
     *
     * @return the value of ljy_user_info.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.username
     *
     * @param username the value for ljy_user_info.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.userIcon
     *
     * @return the value of ljy_user_info.userIcon
     *
     * @mbg.generated
     */
    public String getUsericon() {
        return usericon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.userIcon
     *
     * @param usericon the value for ljy_user_info.userIcon
     *
     * @mbg.generated
     */
    public void setUsericon(String usericon) {
        this.usericon = usericon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.vip
     *
     * @return the value of ljy_user_info.vip
     *
     * @mbg.generated
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.vip
     *
     * @param vip the value for ljy_user_info.vip
     *
     * @mbg.generated
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.rudder
     *
     * @return the value of ljy_user_info.rudder
     *
     * @mbg.generated
     */
    public Integer getRudder() {
        return rudder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.rudder
     *
     * @param rudder the value for ljy_user_info.rudder
     *
     * @mbg.generated
     */
    public void setRudder(Integer rudder) {
        this.rudder = rudder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.guide
     *
     * @return the value of ljy_user_info.guide
     *
     * @mbg.generated
     */
    public Integer getGuide() {
        return guide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.guide
     *
     * @param guide the value for ljy_user_info.guide
     *
     * @mbg.generated
     */
    public void setGuide(Integer guide) {
        this.guide = guide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.attention
     *
     * @return the value of ljy_user_info.attention
     *
     * @mbg.generated
     */
    public Long getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.attention
     *
     * @param attention the value for ljy_user_info.attention
     *
     * @mbg.generated
     */
    public void setAttention(Long attention) {
        this.attention = attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.fans
     *
     * @return the value of ljy_user_info.fans
     *
     * @mbg.generated
     */
    public Long getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.fans
     *
     * @param fans the value for ljy_user_info.fans
     *
     * @mbg.generated
     */
    public void setFans(Long fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.honey
     *
     * @return the value of ljy_user_info.honey
     *
     * @mbg.generated
     */
    public Long getHoney() {
        return honey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.honey
     *
     * @param honey the value for ljy_user_info.honey
     *
     * @mbg.generated
     */
    public void setHoney(Long honey) {
        this.honey = honey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.address
     *
     * @return the value of ljy_user_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.address
     *
     * @param address the value for ljy_user_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.city
     *
     * @return the value of ljy_user_info.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.city
     *
     * @param city the value for ljy_user_info.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.gender
     *
     * @return the value of ljy_user_info.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.gender
     *
     * @param gender the value for ljy_user_info.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.introduction
     *
     * @return the value of ljy_user_info.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.introduction
     *
     * @param introduction the value for ljy_user_info.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.birthDate
     *
     * @return the value of ljy_user_info.birthDate
     *
     * @mbg.generated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.birthDate
     *
     * @param birthdate the value for ljy_user_info.birthDate
     *
     * @mbg.generated
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.creationDate
     *
     * @return the value of ljy_user_info.creationDate
     *
     * @mbg.generated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.creationDate
     *
     * @param creationdate the value for ljy_user_info.creationDate
     *
     * @mbg.generated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.createdBy
     *
     * @return the value of ljy_user_info.createdBy
     *
     * @mbg.generated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.createdBy
     *
     * @param createdby the value for ljy_user_info.createdBy
     *
     * @mbg.generated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.modifyDate
     *
     * @return the value of ljy_user_info.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.modifyDate
     *
     * @param modifydate the value for ljy_user_info.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ljy_user_info.modifiedBy
     *
     * @return the value of ljy_user_info.modifiedBy
     *
     * @mbg.generated
     */
    public Long getModifiedby() {
        return modifiedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ljy_user_info.modifiedBy
     *
     * @param modifiedby the value for ljy_user_info.modifiedBy
     *
     * @mbg.generated
     */
    public void setModifiedby(Long modifiedby) {
        this.modifiedby = modifiedby;
    }
}